language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
before_script:
  - npm install -g npm@latest
  - npm install expo-cli --global
script:
  - yarn install --frozen-lockfile
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      test: skip
      script:
        - yarn install --frozen-lockfile
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - yarn build:ios
